# Generated by Django 5.1.2 on 2024-11-12 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session_year',
            name='session_end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='session_year',
            name='session_start',
            field=models.DateField(),
        ),
    ]
