# Generated by Django 5.1.2 on 2024-11-15 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_student_session_year_id_staff_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_notifications',
            name='status',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
